# Dockerfile

# Use a base image with JDK 21
FROM openjdk:21-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the built JAR file into the container
COPY service-0.0.1-SNAPSHOT.jar /app/kafka-stream.jar

# Expose the application's port
EXPOSE 8080

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "kafka-stream.jar"]
